services:
  web:
    build: .
    ports:
      - "8001:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: education_tech
    ports:
      - "3301:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
